server:
  port: 80
  servlet:
    context-path: /sbssm
  # 错误页，指定发生错误时跳转的URL
  error: 
    path: /error
  # session 最大超时时间（分钟），默认为30分钟
  session: 60

spring: 
  datasource: 
    #基本属性
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chunn?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    default-auto-commit: true
    #指定updates是否自动提交
    auto-commit: true
    maximum-pool-size: 100
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 18800
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
  # 热部署
  devtools: 
    restart: 
      # 热部署生效
      enabled: true    
      # 设置重启的目录,添加那个目录的文件需要restartC
      additional-paths: src/main/java
      # 排除那个目录的文件不需要restart,classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/** 
  # thymeleaf 静态资源配置
  thymeleaf:
    # 关闭缓存，即时刷新，上线生产环境需要改为true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet: 
      content-type: text/html
    

#mybatis为独立节点，不能配置在spring下边
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: org.boot.cnn.dao  # 注意：对应实体类的路径

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
    

 
    