server:
  port: 80
  

spring: 
  datasource: 
    #基本属性
    url: jdbc:mysql://localhost:3306/chunn?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
        
#mybatis为独立节点，不能配置在spring下边
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: org.boot.cnn.dao  # 注意：对应实体类的路径

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
    